package api_test

import (
	"github.com/stretchr/testify/assert"
	"skema-tool/internal/api"
	"testing"
)

const testProtoContent = `
syntax = "proto3";
// Generated by skema-tool. DO NOT EDIT.
package abc.aaa;
{{ .Options }}

import "google/api/annotations.proto";
import "validate/validate.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

// User Defined Protobuf Code Section
service Test1 {
    rpc Heathcheck (HealthcheckRequest) returns (HealthcheckResponse){
        option (google.api.http) = {
          get: "/api/healthcheck"
        };
    }
}

message HealthcheckRequest {
}

message HealthcheckResponse {
    string result = 1;
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
        example: "{\"result\": \"ok\"}"
    };
}
`

func TestGenerateStub(t *testing.T) {
	creator := api.NewGoStubCreator()
	_, err := creator.GenerateStub(testProtoContent, "github.com/skema-dev/test", "teststub")
	assert.Nil(t, err)
	//fmt.Printf("%v\n", result)
}
